package httpcm

import (
    "context"
    "net"
    "net/http"
    "time"
    "io"
)

// RequestCtx carries HTTP-level request state for HCM and HTTP filters.
type RequestCtx struct {
    Context context.Context
    Req     *http.Request
    Remote  net.Addr
    Start   time.Time
    W       io.Writer
    // DownstreamTLS indicates if the downstream connection used TLS.
    DownstreamTLS bool
    // Set by router filter to indicate the chosen upstream cluster.
    UpstreamCluster string
    // If set by router, forwarded path is rewritten to this.
    RewritePath string
    // Responded indicates a filter produced a response.
    Responded bool
    // StatusCode written to downstream (if known).
    StatusCode int
    // UpstreamAddr chosen by router/proxy (host:port) when applicable.
    UpstreamAddr string
    // RequestID propagated/generated by the forwarded-headers filter.
    RequestID string
    // RouteID set by router for per-route options; -1 if unset
    RouteID int
    // RetryOverride set by RouteOptionsFilter, applied by upstream proxy.
    RetryOverride *retryCfg
}

// HTTPFilter is a simple hook that can observe or modify per-request state.
// Returning an error lets the HCM decide how to respond (e.g., 4xx/5xx).
type HTTPFilter interface {
    OnRequest(*RequestCtx) error
}

// Chain runs HTTP filters in order.
type Chain struct{ filters []HTTPFilter }

func NewChain(filters []HTTPFilter) Chain {
    fs := make([]HTTPFilter, len(filters))
    copy(fs, filters)
    return Chain{filters: fs}
}

func (c Chain) Run(rc *RequestCtx) error {
    for _, f := range c.filters {
        if err := f.OnRequest(rc); err != nil {
            return err
        }
    }
    return nil
}
